### ISSUE TITLE
Amazing extension!, just one question

### ISSUE THREAD

**Issue by MatiasFito** [pmneo/ts-importer#1]
Hi, your extension is amazing, the best importer there is currently available. Only question i had was: How can i exclude the tmp folder?.

Because in an app generated with the angular-cli i have a tmp folder full of brocolli .ts files and when the auto import looks for the components them there.

Or maybe not exclude the tmp folder explicitly for allow to select an array of expressions to be matched against when looking for folders to watch.

Thanks for this great extension, if you need some help i am more than willing!. Cheers

**Comment by pmneo** [comment]
I could add a configuration for include patterns and exclude patterns to solve your problem!

**Comment by MatiasFito** [comment]
If you could, that would be awesome. Thanks in advance

**Comment by pmneo** [comment]
Solved with 1.1.0
