### ISSUE TITLE
Don't suggest auto-imports inside comments

### ISSUE THREAD

**Issue by leonadler** [pmneo/ts-importer#10]
_Current behavior:_
When the cursor is inside a comment, typing a symbol that can be exported automatically imports it when pressing space, tab or enter.

_Expected behavior_
When typing inside comments, no import suggestions should be done.

![image](https://cloud.githubusercontent.com/assets/8845620/19762324/d900a48c-9c39-11e6-842f-2d21eb748ac5.png)

My configuration:
- VS Code 1.6.1
- ts-importer 1.2.7
- settings.json:

```
"tsimporter.lowImportance": true,
"tsimporter.spaceBetweenBraces": false
```

Nice work, by the way!

**Comment by pmneo** [comment]
This is on my todo list. The problem is that i have to parse the whole file by myself because vscode does not provide any api for this.

**Comment by pmneo** [comment]
This should do the trick, but sometimes vscode recycles old suggestions which where already resolved before ...
