### ISSUE TITLE
Bug: import code completion doesn't work with 'reflect-metadata'

### ISSUE THREAD

**Issue by MichalLytek** [pmneo/ts-importer#11]
It's a strange issue, I thought that this extension doesn't provide import code completion feature but it was just a bug 😄 

If you have (even commented) line `import "reflect-metadata";` (it's a shim to make TypeScript decorators work) in your file, the import code completion doesn't work at all - there's no suggestion about symbols to import on typing or on `CTRL+SPACE`.

**Comment by MichalLytek** [comment]
And the small, related feature request: import suggestion with decorators - after typing `@`, not only on `CTRL+SPACE` 😉

**Comment by pmneo** [comment]
I will take a look into it!

**Comment by pmneo** [comment]
Please try if the decorators are suggested immediately now

**Comment by MichalLytek** [comment]
Code completion with `import "reflect-metadata";` now works but decorators still aren't suggested immediately as you type `@`. You have to move cursor in different line and then go back an then you will have suggestions as you type the name of the decorator.
