### ISSUE TITLE
Support export default with interfaces

### ISSUE THREAD

**Issue by lukashoegh** [pmneo/ts-importer#12]
Hey

If you want to have an interface as the default export from a file, the syntax is:

`interface Foo { ... }`
`export default Foo;`

At the moment this doesn't work if you try to auto-import it by typing
`let foo: Foo`
 (the interface wont appear in auto complete list). 

Any chance you might implement this feature?

Btw thanks for the nice extension :)

**Comment by pmneo** [comment]
This should not be a big deal!
Am 31.10.2016 14:55 schrieb lukashoegh notifications@github.com:Hey

If you want to have an interface as the default export from a file, the syntax is:

interface Foo { ... }
export default Foo;

At the moment this doesn't work with the exporter (the interface wont appear in auto complete list). Any chance you might implement this feature?

Btw thanks for the nice extension :)

**Comment by lukashoegh** [comment]
I wouldn't have expected it to be :)
