### ISSUE TITLE
Where to put config options and knownSymbols?

### ISSUE THREAD

**Issue by shershen08** [pmneo/ts-importer#13]
Documentation's configuration section contains the description of the plugin's options but no reference where and how to set the.

Should I create a file in project root?
Same about the **knownSymbols** object which can be generated. Where I should add it to make use of ti?

**Comment by pmneo** [comment]
Configuration must be placed into settings.json of your vscode workspace.

The generated known symbols json is only for your information and debugging which symbols the extension has detected.

**Comment by shershen08** [comment]
Thanks @pmneo . Could be helpful to add this to README.md
