### ISSUE TITLE
Feature request: rewrite imports when a typescript file is moved

### ISSUE THREAD

**Issue by frederikschubert** [pmneo/ts-importer#14]
It would be nice if the plugin would rewrite the import paths when a typescript file in the workspace is moved.

**Comment by pmneo** [comment]
This should be part of a refactoring extension ... so i am sorry, no ;)

**Comment by frederikschubert** [comment]
I understand. But would it be possible to create a command that adjusts the import paths for the imports that are selected?

Currently, when I move a file, I have to delete all relative imports, go trough each imported Symbol and add the import back via the quickfix functionality of this plugin.

Say I have these imports.

``` ts
import * as s from "some-npm-module";

import { foo } from "../foo/foo";
import { bar } from "../bar/bar";
...
```

Now I move the containing file one directory down. The relative imports now contain invalid paths.

What I want now is to select the lines containing the now invalid imports and execute a vscode command that looks at the imported symbols in the selection, resolves their location and updates their paths.

**Comment by frederikschubert** [comment]
I had a further look at the code and I think this could be accomplished by matching [this](https://github.com/pmneo/ts-importer/blob/master/src/ImportIndexer.ts#L233) regex against the selected text, lookup the matched symbols against the `ImportIndex`and then use the `Importer` to rewrite the import statement.
I can also work on a PR but have to make myself familiar with the vscode extension API.

**Comment by pmneo** [comment]
First you have to build a reverse index and you have to resolve the relative import to a absolute path. 
You must implement a import remove or replace ... 

Feel free to create a PR ;)

**Comment by frederikschubert** [comment]
Great!! I will try my luck :)
