### ISSUE TITLE
Wrong import statement inserted

### ISSUE THREAD

**Issue by MichalLytek** [pmneo/ts-importer#16]
When I paste part of my code to new file, I have to create necessary imports. This extensions provide support for it:

![2016-11-13 18_51_32-pogoda](https://cloud.githubusercontent.com/assets/10618781/20247673/79028f72-a9d2-11e6-9692-2f2b6abba116.png)

The tooltip statement is appropriate but it insert wrong, default import syntax:

![2016-11-13 18_51_45-pogoda](https://cloud.githubusercontent.com/assets/10618781/20247675/9aa1c9e0-a9d2-11e6-8eaa-ed761b14d4d4.png)

Even when I manually correct the import, the next imports from this module appears as new line with default import syntax.

The trace might be that I had in other file the syntax `import uiRouter, { StateProvider } from "angular-ui-router";` so the cached version might be incorrect. When I removed the mixed statement and reloaded VS Code, the import works ok.

**Comment by pmneo** [comment]
Mixed statements like `import uiRouter, { StateProvider } from "angular-ui-router";` are not supported yet. 

I will take a look into it.

**Comment by pmneo** [comment]
This will not be implemented.
