### ISSUE TITLE
Importing the wrong modules

### ISSUE THREAD

**Issue by reach4thelasers** [pmneo/ts-importer#17]
This plugin was working great for me until yesterday.  Now it is consistently importing stuff I don't want.  I'm not sure what's changed. 

every time I type console._  [logger] it adds:

`imports console as * from 'console' `

because some library I have in my node_modules folder exports a console module.

If I type window._ (global window object) it adds this import.

`imports import { window } from 'rxjs/operator/window';`

Annoying - it was working so well but I had to disable it.  If I can do anything to help diagnose the issue please let me know.

**Comment by pmneo** [comment]
You can try following settings:

"tsimporter.lowImportance": true,

and

"editor.quickSuggestions": false

I also could add a black-list config for suggestions ...
