### ISSUE TITLE
Feature Request: Option to inform style by tslint config.

### ISSUE THREAD

**Issue by joelday** [pmneo/ts-importer#19]
If you can find one and load it, (maybe using tslint itself to do it?) you could override settings that aren't explicitly set in the workspace. That would be cool. Interested in accepting a PR for it? Thanks!

**Comment by pmneo** [comment]
Can you make a example?

I do not exactly understand what you are looking for...

**Comment by DizWARE** [comment]
I would imagine maybe the single to double quote setting falling into this. Also, you can set up rules to order your imports. I imagine this is what @joelday is talking about.

I would be interested in seeing this as well.

**Comment by pmneo** [comment]
No further informations from joelday -> closed.
