### ISSUE TITLE
TSX?

### ISSUE THREAD

**Issue by mikecann** [pmneo/ts-importer#2]
Hey, love the plugin!

Just wondering, is there a specific reason why .tsx files arent supported?

**Comment by pmneo** [comment]
You can adjust the scanned files via tsimporter.filesToScan setting
`tsimporter.filesToScan: [ "**/*.ts", "**/*.tsx" ]`

**Comment by mikecann** [comment]
@pmneo is that in the .vscode/settings.json folder?

**Comment by pmneo** [comment]
Yes, but you have to reopen the workspace after editing that file.

**Comment by mikecann** [comment]
Hmm doesnt seem to work. Is it able to pick up React components listed in other TSX files?

**Comment by pmneo** [comment]
Can you please provide a small sample Project?
Am 28.09.2016 00:58 schrieb Mike Cann notifications@github.com:Hmm doesnt seem to work. Is it able to pick up React components listed in other TSX files?

**Comment by mikecann** [comment]
[tsx-example.zip](https://github.com/pmneo/ts-importer/files/497209/tsx-example.zip)

Run `npm install`, note in index.tsx, im unable to find ComponentA.

**Comment by pmneo** [comment]
Should work now with v1.2.2!
