### ISSUE TITLE
Interface intellisense problem

### ISSUE THREAD

**Issue by 0xphilipp** [pmneo/ts-importer#26]
Hi, when I use this extension it makes using interfaces quite bad. It is probably a bug:

![image](https://cloud.githubusercontent.com/assets/9350951/21993369/c88650ea-dc1a-11e6-8926-6ac19f99a4d0.png)

Expected behavior and when I disable the extension:
![image](https://cloud.githubusercontent.com/assets/9350951/21993387/e2c022c4-dc1a-11e6-8a45-99e33966c5e8.png)

In both screenshots I press ctrl + space within these brakets.

**Comment by pmneo** [comment]
You may take use of the low importance setting.

Von meinem iPad gesendet
