### ISSUE TITLE
ts-importer steals the VSCode status bar space 

### ISSUE THREAD

**Issue by stvnwrgs** [pmneo/ts-importer#27]
Is it possible to add an settings flag to disable the statusbar icon? It's quite useless and just needs a lot of space...

![image](https://cloud.githubusercontent.com/assets/1257443/22714636/beb80e44-ed8d-11e6-82f4-cef88d74b0c9.png)

**Comment by andregs** [comment]
Looks like that should be `tsimporter.showNotifications - Show status notifications, default is false` but it's not working.

**Comment by pmneo** [comment]
New setting noStatusBar will be added. Notifications are popup Messages.
