### ISSUE TITLE
Clean unused (+sort)?

### ISSUE THREAD

**Issue by bickycheese** [pmneo/ts-importer#31]
Hi, much :heart: for the extension! 
Any plans on adding sort + removing unused imports?

**Comment by pmneo** [comment]
No, because ts-lint has this features already implemented: https://palantir.github.io/tslint/rules/ordered-imports/

**Comment by stannynuytkens** [comment]
I agree on the sort but can't find anything on `unused`..

**Comment by pmneo** [comment]
This is already implemented: 
![image](https://cloud.githubusercontent.com/assets/8696493/24496683/30e8ea56-1539-11e7-9016-bfc504784cdd.png)
