### ISSUE TITLE
Can you provide somewhere to customize some index?

### ISSUE THREAD

**Issue by k8w** [pmneo/ts-importer#34]
For example, I always use this:
```typescript
import * as path from 'path';
```

However, it can't auto import `path` when I typed `path`.
I'm not sure if this is a common demand, but think it will be really useful if somewhere I can add some customize index. (Just like the dump index file)

And another problem is that , once use ts-importer, I found that some hint of basic type disappeared.
e.g. I type this:
```typescript
let a: string;
```

Code hint of `string` can not work. While I disable ts-importer it could.

**Comment by pmneo** [comment]
You can specify the order importance of ts-importer: `tsimporter.lowImportance`
