### ISSUE TITLE
Support JavaScript?

### ISSUE THREAD

**Issue by Lxxyx** [pmneo/ts-importer#35]
This project is awesome. I like it and recommend to many friends.
And will you support javascript?

Thank you.

**Comment by pmneo** [comment]
What exactly is the goal? 
Supporting ES2015 Imports/Exports?

**Comment by Lxxyx** [comment]
Yes. Support ES2015 Imports/Exports.

**Comment by pmneo** [comment]
Feel free to create a pull request, i currently don't have the time to implement.
