### ISSUE TITLE
Bug: "tsimporter.doubleQuotes" setting not respected

### ISSUE THREAD

**Issue by axefrog** [pmneo/ts-importer#37]
I have `tsimporter.doubleQuotes` set to false in my settings (which seems redundant seeing as it's the default), but tsimporter still uses double quotes when inserting import statements.

**Comment by pmneo** [comment]
Have you restarted vscode after changing settings?

**Comment by axefrog** [comment]
I did but it didn't make a difference. Anyway I stopped using it because it was throwing too many errors.

**Comment by pmneo** [comment]
Just tested the setting in fresh project with this settings.json:
`{
    "tsimporter.doubleQuotes": true
}` 
and it worked as expected.
