### ISSUE TITLE
Adding custom import statement

### ISSUE THREAD

**Issue by fabiante** [pmneo/ts-importer#40]
Would it be possible to add custom import / export statements?

I work with a custom JS engine that has this import schema

**part.js**
```javascript
var a = 42;
```

**main.js**
```javascript
// #import "part.js"
console.log(a) // Logs 42 to the console
```

In the above script the complete content of the script ```part.js``` is copied into the script ```main.js```. Would this extension be extendable to serve this functionality?

**Comment by pmneo** [comment]
I'm sorry, but this this not planned.
