### ISSUE TITLE
Should not show dependencies in member lists

### ISSUE THREAD

**Issue by codeandcats** [pmneo/ts-importer#44]
Normally when hitting Control + Space (on a Mac) to reveal members for an object VS Code will only show members of the object.

![](https://s1.postimg.org/3giwmj5ytr/ts-importer_disabled.png)

However, when ts-importer is installed it shows all your potential dependencies in your app. In this scenario this is just noise and unfortunately makes the member dropdown almost completely unusable.

![](https://s1.postimg.org/5xuntsisn3/ts-importer_enabled.png)

I love this extension and recommend it to fellow developers but this specific issue is a show stopper for them. Its a shame as I must admit, I feel like ts-importer makes me much more productive with auto importing dependencies, but less productive by getting in the way of member lists. If this issue was fixed I feel like it would make a huge difference in productivity. 🙏

**Comment by pmneo** [comment]
Please try the tsimporter.lowImportance option. 
It is very hard to find out where the suggestion is required and where not.

**Comment by codeandcats** [comment]
Excellent, seems like a reasonable solution, thanks! 👍

CC @tomSawkins
