### ISSUE TITLE
"Importance" of suggestions

### ISSUE THREAD

**Issue by wrygiel** [pmneo/ts-importer#5]
I'm sure if VScode's API allows for that, but would it be possible for the extension's suggestions to be displayed _below_ the "default" suggestions proposed by VScode?

I have removed a single property from the object on the screenshot below to illustrate the point. This one was done without the extension:

![image](https://cloud.githubusercontent.com/assets/2168535/19222165/3dae4678-8e52-11e6-9468-a5c74b7cfa08.png)

And this one with the extension:

![image](https://cloud.githubusercontent.com/assets/2168535/19222168/4d0d94f2-8e52-11e6-97f3-06346df95ed5.png)

**Comment by pmneo** [comment]
Hello, i am sorry but i can not control the order of the items. This is managed by vscode ...

**Comment by wrygiel** [comment]
VSCode developer suggests using [`sortText`](https://github.com/Microsoft/vscode/blob/51c91003717dc10c7c9fe9ee12fd65c780c8d7f0/src/vs/vscode.d.ts#L2303) property for that. Seems a bit hackish at first sight (as in `sortText = "zzz" + label`), but - given the number of suggestions your extension provides - I think the effect would be preferable. What do you think?

**Comment by pmneo** [comment]
I will take a look!
Am 10.10.2016 11:38 schrieb Wojciech Rygielski notifications@github.com:VSCode developer suggests using sortText property for that. Seems a bit hackish at first sight (as in sortText = "zzz" + label), but - given the number of suggestions your extension provides - I think the effect would be preferable. What do you think?

**Comment by wrygiel** [comment]
Works great! Thank you!
