### ISSUE TITLE
High CPU loading after VSCode update to v.1.31.1

### ISSUE THREAD

**Issue by ArtemZag** [pmneo/ts-importer#52]
After updating VSCode to the last version the ts-importer extension became absolutely unusable.
As soon as I enter several symbols in my *.ts file the CPU gets 100% loaded.
(after extension disabling things get normal again)

**Comment by marco4net** [comment]
Not sure if it's the same issue, but for me VSCode becomes extremely slow to respond when typing almost anything in a TS file. Removing the extension resolves the issue. 

When the issue happens, the console log is flooded with thousands of repetitive entries:
[Extension Host] INVALID text edit -> must have at least a label

**Comment by pmneo** [comment]
I am using my extension with VSCode 1.32.3 and Typescript 3.4.1 with a very large Project ( more than 4000 symbols ) without any issues. 

Can anyone provide a sample project which causes the high load?

**Comment by pmneo** [comment]
No infos
