### ISSUE TITLE
tsimporter.filesToExclude not working

### ISSUE THREAD

**Issue by MichalLytek** [pmneo/ts-importer#9]
The `filesToExclude` option is not working for me. I have tried all possibile combinations like `"tsimporter.filesToExclude": [ "./old/**" ]`, `"tsimporter.filesToExclude": [ "old/**" ]` or `"tsimporter.filesToExclude": [ "./old/**/*" ]`. It still resolve also the old project folder:

![2016-10-26 18_24_50-startowa](https://cloud.githubusercontent.com/assets/10618781/19735011/15ec3996-9baa-11e6-9f5b-fa8ba1dded49.png)

Maybe it has cached exports from before I turned the `filesToExclude` setting?

**Comment by pmneo** [comment]
Have you executed the "reindex command" or restarted vscode after changing the settings?

**Comment by MichalLytek** [comment]
I did the `Reload Window` from command pallete. Now reinstalled the extensions and it looks like it's working 😃
